language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - 'pip install -e ".[test]"'
    - 'pip install coveralls'
script:
    - "python ./setup.py nosetests"
after_success:
    - coveralls
